name: IssueTracker
version: 0.5
main: com.mythicacraft.IssueTracker.IssueTracker
commands:
    issue:
        usage: /issue
permissions: 
    issuetracker.issue:
        description: Allows players to create, close, and check issue status
        default: true
    issuetracker.admin:
        description: Allows moderators to check all issues and set the status of each
        default: op
        children:
            issuetracker.issue: true